### ISSUE TITLE
Could not found __resource.lua 

### ISSUE THREAD

**Issue by jason0910854347** [manueljlz/gcphone#100]
I'm new in FiveM
I using this mod and I put the folder where in resource "gcphone"
Do I need to create the  __resource.lua  by myself ?
And where are the "src_htmlPhone" do I put in 

plz teach me!

**Comment by yagizher** [comment]
dont put the file directly. Put https://github.com/manueljlz/gcphone/tree/master/resources/gcphone this in and start it.

**Comment by jason0910854347** [comment]
@yagizher  I put in but there isn't work do I need to put src_htmlPhone in too?

**Comment by yagizher** [comment]
no, dont put src. just put gcphone and start it, it should work.

**Comment by jason0910854347** [comment]
I did but there 's no phone UI somthing weird

**Comment by manueljlz** [comment]
https://github.com/manueljlz/gcphone/releases/tag/V1.3

**Comment by jason0910854347** [comment]
it work tks 
it work tks 
@manueljlz  But I found another bug when someone call you 
the phone does not ringing sound

**Comment by DmACKGL** [comment]
_resource.lua was replaced by fxmanifest due to compatibility issues
Docs: https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/
