### ISSUE TITLE
gcPhone:allUpdate

### ISSUE THREAD

**Issue by xrtw** [manueljlz/gcphone#101]
Citizen.CreateThread(function ()
  while true do
    TriggerServerEvent('gcPhone:allUpdate')
    Citizen.Wait(120000)
  end
end)

for what reasons this was added? i get so much sql job for gcphone now

**Comment by DmACKGL** [comment]
Hi!

This was just a TEMPORARY patch witch is not intended to stay much longer.
I'm working on a better solution right now, this fixes the issue of some players who don't get a phone number when they load.

I sincerely apologies for this really bad solution. 

I hope I get a better fix soon.

**Comment by xrtw** [comment]
ok thanks for answer, but before it worked all great, everytime players get their phone number.
