### ISSUE TITLE
mouse not appearing when change to the mouse mode

### ISSUE THREAD

**Issue by LielXD** [manueljlz/gcphone#103]
like the title says i changed to mouse mode and mouse not appearing and i cant do anything only to open and close the phone help ?

**Comment by recso** [comment]
i had this problem before, and it cost me the whole fivem,
i had to delete the cache from fivem folder and downloaded 1.5gb again

**Comment by LielXD** [comment]
Is there a way to fix it?

**Comment by DmACKGL** [comment]
We don't have a fix right now, We encourage the use of arrows to avoid bugs.

The touch feature was originally created by the creators of GCPHone

**Comment by LielXD** [comment]
i just fix it by changing the name of the folder resource to "gcphone" and its work !!!!
