### ISSUE TITLE
Phone is not opening

### ISSUE THREAD

**Issue by DamskaySteve** [manueljlz/gcphone#108]
Hello, 

I have this error when I want to open my phone, please help me:

I didn't edited anything, tried to reinstall everything :(

https://i.imgur.com/i8flRQU.png

**Comment by DmACKGL** [comment]
Have you changed something in this line?
https://github.com/manueljlz/gcphone/blob/f1cf122a6028cba4f0a3aed2885aca010aa37486/resources/gcphone/config.lua#L9

**Comment by DmACKGL** [comment]
No response, closed.
