### ISSUE TITLE
bug camera

### ISSUE THREAD

**Issue by always91** [manueljlz/gcphone#111]
in sms the photo works does not work on tweeter it would be nice to see it fixed and work :)

**Comment by DmACKGL** [comment]
Hi!

To make the camera work you need to follow this tutorial: https://forum.cfx.re/t/how-to-screenshot-basic-create-image-upload-server-and-use-it-with-gcphone/1025133

**Comment by always91** [comment]
camera message work 
dont camera for tweeter?

**Comment by DmACKGL** [comment]
Check https://github.com/manueljlz/gcphone/issues/92
