### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MCNMATOTA** [manueljlz/gcphone#114]
Hello. I have been trying to install this phoen, but I cant. I don't get what you have to do with the src_htmlPhone. Somebody help me? Thank you.

Hablo español tambien.

**Comment by recso** [comment]
First go and install the original gcphone [https://github.com/N3MTV/gcphone/releases/download/2.21/gcphone.zip](url) , and then install it into your server, then download this gcphone and copy whats inside the src_htmlPhone into your previous gcphone installation.

**Comment by DmACKGL** [comment]
> First go download the original gcphone [https://github.com/N3MTV/gcphone/releases/download/2.21/gcphone.zip](url) , and then install it into your server, then download this gcphone and copy whats inside the src_htmlPhone into your previous gcphone installation.
Very bad call.

You need to download the latest compiled version from here, then move the whole gcphone folder to resources.
https://github.com/manueljlz/gcphone/releases
