### ISSUE TITLE
Update for new es_extended (1.2.0)

### ISSUE THREAD

**Issue by BROTH3RCAST** [manueljlz/gcphone#117]
Can you please update the phone to make it work with the latest version of es_extended (1.2.0)? I have seen that some developpers have done it but I don't like their phone.

**Comment by thefrcrazy** [comment]
> 
> 
> Can you please update the phone to make it work with the latest version of es_extended (1.2.0)? I have seen that some developpers have done it but I don't like their phone.

Hello I am currently using version 1.2.0 of es_extended and it is already compatible since the first version of gcphonev3

**Comment by BROTH3RCAST** [comment]
> > Puoi aggiornare il telefono per farlo funzionare con l'ultima versione di es_extended (1.2.0)? Ho visto che alcuni sviluppatori lo hanno fatto ma non mi piace il loro telefono.
> 
> Ciao Attualmente sto usando la versione 1.2.0 di es_extended ed è già compatibile dalla prima versione di gcphonev3

Hi then I think it's a problem with my server

**Comment by DmACKGL** [comment]
GCPhone works in ES 1.2 Final
