### ISSUE TITLE
Doesn't have a __resource.lua

### ISSUE THREAD

**Issue by AlfaMotorsport** [manueljlz/gcphone#120]
As said above the gcphone v3 doesn't have a __resource.lua so it cannot be loaded on the server, waiting for the owner to upload the file thank you !

**Comment by DmACKGL** [comment]
Hi!
FXManifest its the "new way", probably you aren't using the latest compiled version of this script, download it here: https://github.com/manueljlz/gcphone/releases

More info about fxmanifest: https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/
