### ISSUE TITLE
how to use src_htmlphone ?

### ISSUE THREAD

**Issue by nuengbuster2110** [manueljlz/gcphone#123]
how to use src_htmlphone ?

**Comment by DmACKGL** [comment]
If you don't know how to compile the source code yourself, download the latest compiled version from here: https://github.com/manueljlz/gcphone/releases

**Comment by DmACKGL** [comment]
Otherwise, read the readme.md https://github.com/manueljlz/gcphone/blob/master/src_htmlPhone/README.md
