### ISSUE TITLE
i cant change volume in mumble-voip

### ISSUE THREAD

**Issue by nuengbuster2110** [manueljlz/gcphone#124]
i cant change volume in mumble-voip

**Comment by DmACKGL** [comment]
That's not from us, you need to check the docs available on Mumble's repo.

**Comment by nuengbuster2110** [comment]
Sorry i say about “ringtone”

**Comment by nuengbuster2110** [comment]
I test chang volume from ringtone dont work.

**Comment by DmACKGL** [comment]
Oh, it fixed, but not compiled. I'm going to compile the latest commit ASAP

https://github.com/manueljlz/gcphone/issues/113
