### ISSUE TITLE
ringtone cant change for mumble-voip ?

### ISSUE THREAD

**Issue by nuengbuster2110** [manueljlz/gcphone#125]
ringtone cant change for mumble-voip ? how to fix or use

**Comment by BTNGaming** [comment]
It's because he didn't put the .ogg's into the fxmanifest.lua, Add those and you'll be set.

**Comment by DmACKGL** [comment]
> It's because he didn't put the .ogg's into the fxmanifest.lua, Add those and you'll be set.

https://github.com/manueljlz/gcphone/blob/dbafb174ef357e1dad58891c895016cab4dbc8bb/resources/gcphone/fxmanifest.lua#L73
The manifest is instructed to add all the OGG files located in the sounds folder. Please, read the files well before claiming errors.

About the question, you need to put you oggs on the sound folder and add it to the assets/config/config.json file
