### ISSUE TITLE
Attempt to call nil value _U

### ISSUE THREAD

**Issue by BTNGaming** [manueljlz/gcphone#133]
https://i.imgur.com/4UkIAGn.png

Screenshot says it all, No clue why i'm getting this...

https://i.imgur.com/9qoBMFM.png

**Comment by BTNGaming** [comment]
Any suggestions for this? I've tested this over and over and don't know why this is occurring. (I'm a dev so you don't have to talk to me in lamens terms.)

**Comment by DmACKGL** [comment]
what version of gcphone do you have? try using the latest version.
