### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by Rav3n95** [manueljlz/gcphone#141]
Hey, So i intaled, deleted old sql, i have to phone item too, i press F1 the animation are rigth, i got prop on my hand, but gui are not opening at all, no error on script wise at console. What can i miss?

Edit: I was missing the html folder, any tutorial how can i do it from source files?

**Comment by Rav3n95** [comment]
I know my problem, there is no html part for some reason.

**Comment by SeptJack** [comment]
Same here

**Comment by DmACKGL** [comment]
Download the latest release.zip https://github.com/manueljlz/gcphone/releases
