### ISSUE TITLE
GCPhone not showing up

### ISSUE THREAD

**Issue by LukiePie05** [manueljlz/gcphone#143]
Hi i downloaded all the files and put it in but it still doesnt show up, it only shows up as a prop in my characters hand. i tried getting some help from fivem and they said it was ''Is a script problem, nothing work because there some error on author code''.  and its also an html problem. Pls anwer as fast as you can, i really like the phone.

**Comment by DmACKGL** [comment]
https://github.com/manueljlz/gcphone/releases/tag/V1.4.1 Download Resources.zip

**Comment by LukiePie05** [comment]
It still doesnt work
