### ISSUE TITLE
warning / big problem 

### ISSUE THREAD

**Issue by fucekar** [manueljlz/gcphone#149]
when i try to massage a job i got that warning(print) in my console
cfx> = WARNING = Appels sur un service non enregistre => numero : ambulance
= WARNING = Appels sur un service non enregistre => numero : police
and sms not sended
what do i do? thanks

**Comment by DmACKGL** [comment]
Did you install the esx_gcphone_addon resource?
https://github.com/N3MTV/gcphone/tree/master/resources/esx_addons_gcphone
