### ISSUE TITLE
Phone keybind issue

### ISSUE THREAD

**Issue by FakeItalianMan** [manueljlz/gcphone#170]
Hello I have GCPhone and it's keybound to F1 but for some reason when I press F1 to pull the phone up it opens but my minimap also extends larger any ideas on how to fix this? Thanks.

**Comment by MaDHouSe79** [comment]
Hi, i dont know if you alreadxy fix it, but go to client.lua about line 669 and
find all: SetBigmapActive and put -- before it, you uncomment it out and the map stay as it is ;)

--SetBigmapActive(1,0)  <--- Like this.
--SetBigmapActive(0,0) <--- and like this.

hope it helps

**Comment by FakeItalianMan** [comment]
Thank you.
