### ISSUE TITLE
Not generating numbers 

### ISSUE THREAD

**Issue by aleexnl** [manueljlz/gcphone#18]
I don't get numbers. It's a Null value in the database
![image](https://user-images.githubusercontent.com/50357555/80332816-35d0f480-884c-11ea-9270-ee01b4603b9e.png)

Also when they call to a service like police we can't listen each other.

**Comment by ArviinM** [comment]
You need essential mode

**Comment by Natesept26** [comment]
Did you ever get figured out?

**Comment by aleexnl** [comment]
Downloaded a modified version of a fork. Search for it.
