### ISSUE TITLE
phone number dont shows up

### ISSUE THREAD

**Issue by blockhander3** [manueljlz/gcphone#32]
Me and my players dont have phone number, it shows only ###-####, but in the db all of players have number

**Comment by camilopr11** [comment]
do u have solve this issue? i'm having same problem

**Comment by mrcharasi** [comment]
Same issue

**Comment by Natesept26** [comment]
Did anyone figure out the fix?

**Comment by manueljlz** [comment]
Try testing the latest version

https://github.com/manueljlz/gcphone/releases

**Comment by Morfiiii** [comment]
I tried to install the last version. It works, until I restarded the server, now I still having the issue.
