### ISSUE TITLE
Can not take photo... Keep Freezing

### ISSUE THREAD

**Issue by Berkeratay** [manueljlz/gcphone#35]
Hi i Installed;

Screenshot Basic and all dependencies from this link
https://forum.cfx.re/t/how-to-screenshot-basic-create-image-upload-server-and-use-it-with-gcphone/1025133

The app_message_send_photo option is not working in messages, it opens the camera and when I press something it get’s stuck. I can not take any pictures at all. Can not move.
Need to restart gcphone and even that won't solve the problem since numbers are gone.

Please help about to lose my mind.

**Comment by josh-tf** [comment]
Having this issue as well, have tried a few things. Following

**Comment by DmACKGL** [comment]
Hey @Berkeratay, and @josh-tf!

I'm glad to announce the fix https://github.com/DmACKGL/gcphone-1/commit/ccbc795db0f9148bbaaa45a0b5b72728b6ceda95
