### ISSUE TITLE
Can't messages and calls

### ISSUE THREAD

**Issue by arwent** [manueljlz/gcphone#42]
Hello there,

I have the latest es_extended v1 final, when I sent a message, the receiver does not receive the message instant. I need to restart the resource and this is here the receiver can access the message. For the call, it is the same thing, I can call, I have the waiting tone but nothing at the receiver.

**Comment by 4Trout** [comment]
@arwent +1 also having this issue on extendedmode..Let me know if you resolve it and so will I!

**Comment by Mol3kule** [comment]
Same here

**Comment by manueljlz** [comment]
https://github.com/manueljlz/gcphone/releases

fixed up
