### ISSUE TITLE
Ringtone not working

### ISSUE THREAD

**Issue by Skyanics** [manueljlz/gcphone#51]
I am unable to hear the ringtone while being called. Everyone in the server has this issue. Any way to solve this problem?

**Comment by Parity-lab** [comment]
Same here

**Comment by Parity-lab** [comment]
Do you fix it?

**Comment by Skyanics** [comment]
> Do you fix it?

Nope not yet, still looking for an answer but if I figure it out I'll let you know

**Comment by Parity-lab** [comment]
Thank you, I will also say notice when I have fixed it. I think this is due to FiveM because with our loadingscreen the music in .odd format is no longer possible

**Comment by krnage** [comment]
Same here

**Comment by Parity-lab** [comment]
The funny thing is, all the other sounds from the phone go except the ringtones. So the Twitter sounds etc. xD

**Comment by Parity-lab** [comment]
https://github.com/manueljlz/gcphone/issues/51

**Comment by kielerboy** [comment]
this is a fivem problem   here is the text from fivem discord    

> NUI audio/video issues. This is due to use of proprietary codecs (MP3/H.264/MP4), these are not supported in Chromium and only worked in old M73 by coincidence. Not likely to be fixed, ask Google for supporting these. MPEG LA patents are way out of our budget, and alternately we'd have to block downloading of FiveM/RedM in the US and other regions where software patents are legal. Also, some OGG files are badly converted and still have mp4 tags in them.

**Comment by LordXenaroth** [comment]
finally I found someone with my same problem, did you find any solution?

**Comment by Skyanics** [comment]
> finally I found someone with my same problem, did you find any solution?
Nope not yet

**Comment by Parity-lab** [comment]
So the way I understood it, it's just the ODD. files have been blocked containing the tracks of an MP4 file. I try it the days with non-copyright songs in ODD. format

**Comment by ZockerBoysHD** [comment]
convert them to webm or do the ogg format properly. or even upload them on a webserver and put the links isntead of files there

**Comment by LordXenaroth** [comment]
@ZockerBoysHD still not working for me

**Comment by Ren0X1** [comment]
any fix?

**Comment by manueljlz** [comment]
we are in it, trying to configure and see the cause of the failure, it
seems to be due to update five, but we are in it

**Comment by DmACKGL** [comment]
Possible fix https://github.com/manueljlz/gcphone/issues/56#issuecomment-657144081

**Comment by DmACKGL** [comment]
Branch Created for this issue: https://github.com/manueljlz/gcphone/tree/RingtoneFix

**Comment by DmACKGL** [comment]
Hey Everyone!

We have found a temporary fix using the ring2.ogg file as the default ringtone. We are working on figuring out how to port customs songs to working ringtones.

**Comment by DmACKGL** [comment]
Fix #79

**Comment by SimonBaeza** [comment]
vMenu Off
