### ISSUE TITLE
No Ringtone

### ISSUE THREAD

**Issue by Brandidiot** [manueljlz/gcphone#56]
No one hears their phone ring.

**Comment by LordXenaroth** [comment]
Same problem for me

**Comment by xoomer** [comment]
![image](https://user-images.githubusercontent.com/7227325/87222963-e5206080-c391-11ea-9147-0148ae785983.png)

Fivem developer said  this

**Comment by Brandidiot** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7227325/87222963-e5206080-c391-11ea-9147-0148ae785983.png)
> 
> Fivem developer said this

idk if it's as serious as that, it seems like only admins aren't able to hear the ringtones, regular players can. I thought it was vMenu since that was causing issues with us not being able to hear anyone when they called, but even after removing vMenu completely admins still can't hear the ringtone. Idk what it could be at this point.

**Comment by Brandidiot** [comment]
alright so it seems like it was either easyadmin or esx_admin2 causing the issue. So I had to disable vMenu voice chat and uninstall easyadmin and esx_admin2, now it's working and all good.
