### ISSUE TITLE
save contacts

### ISSUE THREAD

**Issue by tobipazos25** [manueljlz/gcphone#59]
Hi! When i try to save a contact, it doesnt save, it just stays as nothing, no error pops up in the console or F8, any idea?
thanks!!

**Comment by BuddiesTV** [comment]
same Proplem.

**Comment by DmACKGL** [comment]
https://github.com/manueljlz/gcphone/blob/072bc07bd52686e08a099e26ce478efc0ad5281f/src_htmlPhone/src/components/contacts/Contact.vue#L104

Change this line for `this.addContact({` and rebuild.

**Comment by DmACKGL** [comment]
Fixed on https://github.com/manueljlz/gcphone/commit/373959010efc911e321fedad69a36098ef51fc7f

**Comment by manueljlz** [comment]
ok thx ^^
