### ISSUE TITLE
fixed some errors

### ISSUE THREAD

**Issue by AYZNN** [manueljlz/gcphone#60]
hey i fixed some errors with the latest version
- Addd Contact display
- Twitter SQL incrementation
- Calls history
- a console error

reply me if you want the code :) thx

**Comment by tobipazos25** [comment]
i cant save contacts, did you manage to fix that?

**Comment by manueljlz** [comment]
Upload it to my git for me to review and merge it. thank you

**Comment by AYZNN** [comment]
how can i do that ? sry i didnt use github

**Comment by DmACKGL** [comment]
> how can i do that ? sry i didnt use github

Hi!
Create a new repo [HERE](https://github.com/new) and follow the instructions. After you commit the changes and pushed to your repository paste the link here.

**Comment by AYZNN** [comment]
lemme some mns ^^

**Comment by AYZNN** [comment]
https://github.com/AYZNN/gcphonev3 enjoy :)

**Comment by AYZNN** [comment]
i've added some sound too when u slide up down etc

**Comment by DmACKGL** [comment]
Can you upload the src_html folder too? (In that way we can run diffs and see what's changed.

**Comment by AYZNN** [comment]
https://github.com/AYZNN/gcphonev3/tree/master/html here ?

**Comment by DmACKGL** [comment]
> https://github.com/AYZNN/gcphonev3/tree/master/html here ?

That's the compiled version. What I mean it's something like this https://github.com/manueljlz/gcphone/tree/master/src_htmlPhone

**Comment by AYZNN** [comment]
you ask me too much lol
