### ISSUE TITLE
Index a nil value (local 'xplayer')

### ISSUE THREAD

**Issue by DmACKGL** [manueljlz/gcphone#69]
Issue: nil value (local 'xplayer')
How to replicate: Reload gcphone (restart gcphone)
File (if known): server.lua
Line (if known): 546
https://github.com/manueljlz/gcphone/blob/7be676eff740f9ad818c9d51ef281bd112847e56/resources/gcphone/server/server.lua#L546
Screenshot of the issue (if available):
![Server Console](https://user-images.githubusercontent.com/10565361/87472056-53ad2a80-c5ed-11ea-8778-aac4ac90980e.png)

**Comment by DmACKGL** [comment]
After testing a lot of times, the issue doesn't always happen.
A try-catch in server and client-side should do the trick.

**Comment by DiabolicAngeL** [comment]
> After testing a lot of times, the issue doesn't always happen.
> A try-catch in server and client-side should do the trick.

I have this error every time my character is loading in the game.
Using latest version.
