### ISSUE TITLE
Javascript Alert

### ISSUE THREAD

**Issue by DmACKGL** [manueljlz/gcphone#74]
Issue: Phone Freeze and alert showed.
How to replicate: Selection number on History
File (if known):
Line (if known): 
![image](https://user-images.githubusercontent.com/10565361/87485069-e78af080-c605-11ea-90f3-2c4ae06c30f7.png)

**Comment by DmACKGL** [comment]
Should be fixed on https://github.com/manueljlz/gcphone/pull/73

**Comment by manueljlz** [comment]
It was already solved 90571669a03400d481159cf57769f32d042c7b25
