### ISSUE TITLE
Change contacts icons (Help/Can't make it work)

### ISSUE THREAD

**Issue by DiabolicAngeL** [manueljlz/gcphone#77]
I am trying to change the contact icons and also add a taxi icon but it doesn't work.
I don't know what i am doing wrong.

1. I uploaded my icon in `gcphone/html/static/img/icons_app` _(Made in photoshop same size as police icon)_
2. I added the icon in **fxmanifest.lua** `'html/static/img/app_tchat/taxi.png',`
3. I edited **config.json** _(Like the Police and ambulance contacts are, I just added the icon line)_:

**Service call**
```{
"display": "Taxi",
"backgroundColor": "yellow",
"icon": "/html/static/img/icons_app/taxi.png",
"subMenu": [{
"title": "Send a message",
"eventName": "esx_addons_gcphone:call",
"type": {
"number": "taxi"
```
**defaultContacts**

```{
"number": "taxi",
"display": "Taxi",
"backgroundColor": "yellow"
"icon": "/html/static/img/icons_app/taxi.png"
```

When I have the icon lines on both `Service call` and `defaultContacts` the phone opens but everything is empty, no apps etc. When I remove the icon line from `defaultContacts` the phone works but the icon appears empty.

It may something too easy, but I just can't find what i'm doing wrong or if I'm missing something here.
Thanks!

**Comment by manueljlz** [comment]
[image: image.png]
The route is poorly defined

**Comment by DiabolicAngeL** [comment]
> [image: image.png] The route is poorly defined

Hello, sorry, what do you mean? (Newbie)
