### ISSUE TITLE
Taking picture not working!

### ISSUE THREAD

**Issue by AgenChicken24** [manueljlz/gcphone#82]
Hello and ty for helping. So i am trying to make the picture option work but with no success if anyone can help me out i will be thankful. I have add this part in the client.lua but it does not work!
![image](https://user-images.githubusercontent.com/64702468/87615300-1777e800-c71b-11ea-8c46-a7129a1565be.png)

![image](https://user-images.githubusercontent.com/64702468/87615328-29598b00-c71b-11ea-909f-a3186b8db940.png)
I am receiving an error screenshot basic failed to fetch

**Comment by DmACKGL** [comment]
Hi!

Follow this tutorial: https://forum.cfx.re/t/how-to-screenshot-basic-create-image-upload-server-and-use-it-with-gcphone/1025133

**Comment by DmACKGL** [comment]
Hi!

I'm not sure about imgur compatibility, but you can use this solution to make the camera work.
https://forum.cfx.re/t/how-to-screenshot-basic-create-image-upload-server-and-use-it-with-gcphone/1025133
