### ISSUE TITLE
i still have phone object problem...

### ISSUE THREAD

**Issue by YInfeRnal** [manueljlz/gcphone#84]
when i open the phone phone open and work fine but the phone object not coming to my hand and i dont it in my hand
:|

**Comment by DmACKGL** [comment]
Known Bug, we are working on it :D

**Comment by YInfeRnal** [comment]
why not telling? :D :D :D
i searching about 2/3 day to it and i think thats my problem not resource problem
FUUUUCK :D :D :D
yea i waiting thanks guys for your very good phone ****

**Comment by manueljlz** [comment]
THX men

**Comment by WnDSolutions** [comment]
@YInfeRnal @manueljlz 

Open `gcphone/client/animation.lua` and replace `"prop_amb_phone"` with `-1038739674`

```
local phoneProp = 0
local phoneModel = -1038739674
-- OR "prop_npc_phone"
-- OR "prop_npc_phone_02"
-- OR "prop_cs_phone_01"
```

Also something else I found

From `config.json` the **English** Language is missing the following:

```
      "APP_MESSAGE_MESS_SMS": "SMS",
      "APP_MESSAGE_MESS_CALL": "Call",
      "APP_MESSAGE_MESS_COPY": "Copy",
```

**Comment by DiabolicAngeL** [comment]
@YInfeRnal @manueljlz

Open `gcphone/client/animation.lua` and replace `"prop_amb_phone"` with `-1038739674`

```
local phoneProp = 0
local phoneModel = -1038739674
-- OR "prop_npc_phone"
-- OR "prop_npc_phone_02"
-- OR "prop_cs_phone_01"
```

Also something else I found

From `config.json` the **English** Language is missing the following:

```
      "APP_MESSAGE_MESS_SMS": "SMS",
      "APP_MESSAGE_MESS_CALL": "Call",
      "APP_MESSAGE_MESS_COPY": "Copy",
```

**Comment by DmACKGL** [comment]
Fix on https://github.com/manueljlz/gcphone/commit/96795769e55510b25612bd942f1b19acc40974e9

**Comment by YInfeRnal** [comment]
> @YInfeRnal @manueljlz @DmACKGL
> 
> Open `gcphone/client/animation.lua` and replace `"prop_amb_phone"` with `-1038739674`
> 
> ```
> local phoneProp = 0
> local phoneModel = -1038739674
> -- OR "prop_npc_phone"
> -- OR "prop_npc_phone_02"
> -- OR "prop_cs_phone_01"
> ```
> 
> ![image](https://user-images.githubusercontent.com/68332732/87711649-d7127b80-c7a7-11ea-9bd6-2a22f9f72b09.png)

this fixed the problem thanks
