### ISSUE TITLE
Phone not Opening (But the Animation plays)

### ISSUE THREAD

**Issue by BuddiesTV** [manueljlz/gcphone#85]
Hey when i press F1 the phone animation plays, but the phone is not opening...
https://streamable.com/7f3cb3

**Comment by thefrcrazy** [comment]
> 
> 
> Hey when i press F1 the phone animation plays, but the phone is not opening...
> https://streamable.com/7f3cb3

https://github.com/manueljlz/gcphone/issues/25#issuecomment-640078636

**Comment by BuddiesTV** [comment]
This is not the solution, the phone is not opening

**Comment by DmACKGL** [comment]
Hi!

Can you check the console of your server for any GCPhone errors?

**Comment by TheFinderFake** [comment]
I can also confirm, the animation will play but the phone doesn't open. In the F8 console it will just say constantly about every 5 seconds or so "Actualizando GCP" and never pull the phone model out or bring the phone up on the screen. There are no errors as far as I can see though, like flat out big errors.

**Comment by DmACKGL** [comment]
> I can also confirm, the animation will play but the phone doesn't open. In the F8 console it will just say constantly about every 5 seconds or so "Actualizando GCP" and never pull the phone model out or bring the phone up on the screen. There are no errors as far as I can see though, like flat out big errors.

Please download the de latest version and try again:
https://github.com/manueljlz/gcphone/releases/tag/V1.3

The error you are mentioning never have happened to me, I'm going to check again anyway.

**Comment by TheFinderFake** [comment]
Wait, after putting the files back in again after redownloading them, I think it was just a corrupted file somehow, it works now completely. At least my issue is fixed. Not sure about the OP here.

**Comment by manueljlz** [comment]
Well !!, if you want to open the topic in git to see if any other user has
the same problem, we are currently very attentive to all the problems that
come up. Thanks for trusting us.

**Comment by BuddiesTV** [comment]
Reinstalling & Clearing the cache is not solving the issue but in the console is no error

**Comment by alexjose70** [comment]
Did you solve the problem? Can you tell us what files are you placing on your gcphone folder? (Creo que hablas español)

**Comment by BuddiesTV** [comment]
No, i dont solve the problem :/

**Comment by alexjose70** [comment]
Please, post a picture of what is inside of gcphone folder.

**Comment by BuddiesTV** [comment]
Sure: https://prnt.sc/tjgu4w

**Comment by alexjose70** [comment]
The problem is that you dont have the HTML folder. You need to compile the source first or download the compiled version. So, can you tell me the URL you used for downloading the script?

**Comment by BuddiesTV** [comment]
Can you say me how to install the hole phone, i run this commands and it dosent work

**Comment by TheFinderFake** [comment]
Like alexjose said, it might be better if you just download the compiled files if you're new to doing compiles with source code. Go to the link that Dm posted earlier: https://github.com/manueljlz/gcphone/releases/tag/V1.3 and make sure that you download the "resources.zip" file and then make sure to drag out the folder called "gcphone" and use that, not the "resources" folder. I hope this makes sense. I can post a few SS's if it would help. If it is still not working, we might need some more screen shots of what the issue could be from both your console log and in game F8 console when trying to open the phone.

**Comment by BuddiesTV** [comment]
OMG, thank you, idk that i am using the sources ^^ I'm stupid

**Comment by BuddiesTV** [comment]
The issue is solved
