### ISSUE TITLE
Phone calls, cant hear admins

### ISSUE THREAD

**Issue by alexjose70** [manueljlz/gcphone#90]
Hi guys,

I am trying to call as admin, but the others users or other admins, cant hear. Do you know anything about this issue?

**Comment by manueljlz** [comment]
Hi, how is this with the latest version? If so, we start looking for the
fault. thank you

**Comment by alexjose70** [comment]
Manuel, muchas gracias por responder. 
Thank you a lot for reply. 

Actually, I am using the last version.

I am trying to go into your code to fixing it. 
I am new on FiveM and Lua, so, Sorry for delaying on this and bother you.

I think that there is a problem with the annimation.

when you initialize the phone, it doesn't work. But, the phone is shown on the hand for some seconds when you press esc after trying to taking the photo.

**Comment by alexjose70** [comment]
About the phone texture. it seems that the solution is:
delete these from the file fxmanifest.lua

fx_version 'bodacious'

game 'gta5'


and change the name fxmanifest.lua to __resource.lua

**Comment by recso** [comment]
> About the phone texture. it seems that the solution is:
> delete these from the file fxmanifest.lua
> 
> fx_version 'bodacious'
> 
> game 'gta5'
> 
> and change the name fxmanifest.lua to __resource.lua

@alexjose70 
is this a fix for the phone to be shown in the hands of the players?

**Comment by alexjose70** [comment]
> > About the phone texture. it seems that the solution is:
> > delete these from the file fxmanifest.lua
> > fx_version 'bodacious'
> > game 'gta5'
> > and change the name fxmanifest.lua to __resource.lua
> 
> @alexjose70
> is this a fix for the phone to be shown in the hands of the players?

Yes. With this, you can see the phone on the hands players.

**Comment by DmACKGL** [comment]
> About the phone texture. it seems that the solution is:
> delete these from the file fxmanifest.lua
> 
> fx_version 'bodacious'
> 
> game 'gta5'
> 
> and change the name fxmanifest.lua to __resource.lua
Better Fix on: https://github.com/manueljlz/gcphone/commit/3c2d0091c8f07f9fc42c91dbee8661b28de07d02
@alexjose70 @recso

**Comment by alexjose70** [comment]
I appreciate this a lot. I think that I got an error after importing {Howl} The phone just brokes.

Do you know how to fix that?

**Comment by alexjose70** [comment]
So, I think I fixed it. On VoiceRCT you must declare new Howl({}). (line 15).

**Comment by alexjose70** [comment]
I tested this version and I still don't have sound on the admins using webrtc. I tried to move to VoIP, but not working neither. Do you have any method to test this behavior with only one PC?

**Comment by alexjose70** [comment]
I finally realized what was the problem. vMenu and Gcphone create problems. vMenu’s voice channels conflict to the others voice chat channels. I think if we want to talk by GCphone, you must use esx_voice.
