### ISSUE TITLE
onMySQLReady

### ISSUE THREAD

**Issue by xrtw** [manueljlz/gcphone#98]
AddEventHandler('onMySQLReady', function ()
    MySQL.Async.fetchAll("DELETE FROM phone_messages WHERE (DATEDIFF(CURRENT_DATE,time) > 10)")
end)

seems not working, or maybe how it works ?

**Comment by yagizher** [comment]
use MySQL.ready(function ()

**Comment by xrtw** [comment]
> use MySQL.ready(function ()

thanks

**Comment by yagizher** [comment]
So close the issue?

**Comment by xrtw** [comment]
what does > 10 mean? 10 days, 10 weeks?
